services:
  hockeyteeth-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: hockeyteeth-api/production-0.0.0
    environment:
      JAR_FILE: api-0.0.1-SNAPSHOT.jar
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SPOTIFY_API_CLIENT_ID: ${SPOTIFY_API_CLIENT_ID}
      SPOTIFY_API_CLIENT_SECRET: ${SPOTIFY_API_CLIENT_SECRET}
    ports:
      - "8080:8080"
