services:
  hockeyteeth-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: hockeyteeth-api
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SPOTIFY_API_CLIENT_ID: ${SPOTIFY_API_CLIENT_ID}
      SPOTIFY_API_CLIENT_SECRET: ${SPOTIFY_API_CLIENT_SECRET}