name: Deploy API for Production

on:
  push:
    branches: [ "main" ]
    paths: [ "api/hockey-teeth/**" ]

permissions:
  id-token: write
  contents: read

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - name: Set Up Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.2.1

    - name: Build the Docker image
      working-directory: api/hockey-teeth
      run: |
        ./gradlew build
        docker-compose build

    - name: Verify the Image
      run: docker images

    - name: Set Up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-deploy
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-west-2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'

    - name: Tag and Push Image
      env:
        REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
        REPOSITORY: hockeyteeth-api-production
        IMAGE_TAG: latest
      run: |
        aws sts get-caller-identity
        docker tag REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY
        docker push $REGISTRY/$REPOSITORY